spring.application.name=study

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true

jwt.secret=a2c4b8e9d1f3g5h7j9k2l4m6n8p0q2r4s6t8u0v2w4x6y8z0A2B4C6D8E0F2G4H6
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=1209600000

google.client-id=241254360000-m4opj6urgocis06el91deu5qjk5s3qu0.apps.googleusercontent.com
