spring.application.name=StudyGroup
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=studygroup-studygroup-studygroup-studygroup-secret-key-2026
jwt.access-token-expiration=3600000
google.client-id=241254360000-m4opj6urgocis06el91deu5qjk5s3qu0.apps.googleusercontent.com

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.messages.encoding=UTF-8
